dist: xenial

language: java

matrix:
  include:
    - jdk: openjdk8
      env: SKIP_RELEASE=false
    - jdk: openjdk11
      env: SKIP_RELEASE=true

branches:
  #Don't build tags
  except:
    - /^v\d.*$/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_install:
  - "openssl aes-256-cbc -K ${encrypted_35d5c0204248_key} -iv ${encrypted_35d5c0204248_iv} -in private.key.enc -out ./private.key -d && gpg --import ./private.key || echo"

install:
  - ./gradlew --version # Display Gradle, Groovy, JVM and other versions

script:
  - ./gradlew --scan --stacktrace --warning-mode=all build

after_success:
  - "./gradlew --scan publish -x check"
